/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    name VARCHAR(100),
    id INT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    date_of_birth DATE,
    escape_attempts INT,
    neutered BOOLEAN,
    weight_kg DECIMAL
);
